"""init

Revision ID: 44acaf729ac1
Revises: 38baf534ae3b
Create Date: 2024-05-30 11:13:22.486578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44acaf729ac1'
down_revision: Union[str, None] = '38baf534ae3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userse_email'), 'userse', ['email'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'userse', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_index(op.f('ix_userse_email'), table_name='userse')
    op.drop_table('userse')
    # ### end Alembic commands ###
